[workspace]

members = [
"analyzer",
"classifier",
"codec",
"emysound",
"hls-fetcher",
"mfcc",
"model",
"ndarray-shuffle",
"restreamer",
"tag_analyser",
"tags",
"unstreamer"]

exclude = ["mongodb2sqlite"]

[workspace.dependencies]
ac-ffmpeg = "0.18.1"
anyhow = "1.0.69"
async-stream = "0.3.3"
async-trait = "0.1.64"
aubio = { version = "0.2.1", features = ["pkg-config"] }
bson = "2.5.0"
bytemuck = "1.13.0"
clap = { version = "4.1.4", features = ["derive"] }
criterion = "0.4.0"
flume = { version = "0.10.14", default-features = false }
futures = { version = "0.3.26" }
hls_m3u8 = "0.4.1"
humansize = { version = "2.1.3", features = ["impl_style"] }
itertools = "0.10.5"
kdam = "0.3.0"
lazy_static = "1.4.0"
lofty = "0.11.0"
log = "0.4.17"
mime = "0.3.16"
mongodb = { version = "2.3.1", features = ["bson-uuid-0_8", "bson-chrono-0_4"] }
multipart = { version = "0.18.0", default-features = false, features = ["client"] }
ndarray = { version = "0.15.6", features = ["serde"] }
ndarray-stats = "0.5.1"
numpy = "0.18.0"
pyo3 = { version = "0.18.0", features = ["auto-initialize"] }
rand = { version = "0.8.5", features = ["small_rng", "simd_support"] }
rayon = { version = "1.6.1" }
regex = "1.7.1"
rusqlite = { version = "0.28.0", features = ["bundled", "blob", "i128_blob", "time"] }
serde = { version = "1.0.152", features = ["derive"] }
serde-pickle = "1.1.1"
serde_json = "1.0.92"
serde_with = "2.2.0"
thiserror = "1.0.38"
time = "0.3.17"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread", "fs", "signal"] }
tower = "0.4.13"
tower-http = { version = "0.3.5", features = ["full"] }
ulid = "1.0.0"
ureq = { version = "2.6.2", features = ["json"] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }

analyzer = { version = "*", path = "./analyzer" }
classifier = { version = "*", path = "./classifier" }
codec = { version = "*", path = "./codec" }
mfcc = { version = "*", path = "./mfcc" }
model = { version = "*", path = "./model" }
tags = { version = "*", path = "./tags" }
unstreamer = { version = "0.1.0", path = "./unstreamer" }
