[workspace]
resolver = "2"

members = [
"analyzer",
"classifier",
"codec",
"mfcc",
"restreamer",
"tools",
"unstreamer"]

exclude = ["mongodb2sqlite"]

[workspace.dependencies]
ac-ffmpeg = "0.18.1"
anyhow = "1.0.71"
async-stream = "0.3.5"
async-trait = "0.1.68"
axum = { version = "0.6.18" }
aubio = { version = "0.2.1", features = ["pkg-config"] }
bincode = "1.3.3"
bson = "2.6.1"
bytemuck = "1.13.1"
chrono = "0.4.26"
clap = { version = "4.3.4", features = ["derive"] }
criterion = "0.5.1"
derive_builder = { version = "0.12.0", features = ["clippy"] }
flume = { version = "0.10.14", default-features = false }
futures = { version = "0.3.28" }
hls_m3u8 = "0.4.1"
humansize = { version = "2.1.3", features = ["impl_style"] }
itertools = "0.10.5"
kdam = "0.3.0"
lazy_static = "1.4.0"
lofty = "0.14.0"
log = "0.4.19"
mime = "0.3.17"
multipart = { version = "0.18.0", default-features = false, features = ["client"] }
ndarray = { version = "0.15.6", features = ["serde"] }
ndarray-shuffle = { version = "*", git = "https://github.com/AKhranovskiy/ndarray-shuffle.git" }
ndarray-stats = "0.5.1"
numpy = "0.19.0"
os_pipe = "1.1.4"
pyo3 = { version = "0.19.0", features = ["auto-initialize"] }
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = { version = "1.7.0" }
regex = "1.8.4"
rusqlite = { version = "0.29.0", features = ["bundled", "blob", "i128_blob", "time"] }
serde = { version = "1.0.164", features = ["derive"] }
serde-pickle = "1.1.1"
serde_json = "1.0.96"
serde_with = "3.0.0"
stderrlog = "0.5.4"
thiserror = "1.0.40"
time = { version = "0.3.22", features = ["formatting", "local-offset"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread", "fs", "signal"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["full"] }
ulid = "1.0.0"
ureq = { version = "2.7.0", features = ["json"] }
url = { version = "2.4.0", features = ["serde"] }
uuid = { version = "1.3.4", features = ["v4", "serde"] }

analyzer = { version = "*", path = "./analyzer" }
classifier = { version = "*", path = "./classifier" }
codec = { version = "*", path = "./codec" }
mfcc = { version = "*", path = "./mfcc" }
model = { version = "*", path = "./model" }
tags = { version = "*", path = "./tags" }
unstreamer = { version = "*", path = "./unstreamer" }
