[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
rocket = { version = "0.5.0-rc.2", features = ["msgpack", "uuid", "json"] }
uuid = { version = "1.1.0", features = ["v4"] }
rocket_cors = "0.6.0-alpha1"
serde = { version = "1.0.137", features = ["derive"] }
simplelog = "0.12.0"

[dependencies.model]
version = "*"
path = "../model"
