[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"
description = "Fetch audio data from the remote source"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
