[package]
name = "analyzer"
version = "0.5.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ac-ffmpeg = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
classifier = { workspace = true }
codec = { workspace = true }
mfcc = { workspace = true }
ndarray = { workspace = true }
ndarray-stats = { workspace = true }
time = { workspace = true }
unstreamer = { workspace = true }
url = { workspace = true }
