[package]
name = "analyzer"
version = "0.2.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ac-ffmpeg = { workspace = true }
anyhow = { workspace = true }
bytemuck = { workspace = true }
ndarray = { workspace = true }
ndarray-stats = { workspace = true }

[dependencies.classifier]
path = "../classifier"

[dependencies.mfcc]
path = "../mfcc"
