[package]
name = "emysound"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
bytes = "1.1.0"
log = "0.4.17"
reqwest = { version = "0.11.10", features = ["json", "multipart"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.18.2", features = ["full", "fs"] }
uuid = { version = "1.1.0", features = ["v4"] }
