[package]
authors = { workspace = true }
edition = { workspace = true }
name = "classifier"
version = "0.9.0"

[dependencies]
anyhow = { workspace = true }
ndarray = { workspace = true }
tensorflow = { workspace = true }
