[package]
name = "classifier"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
lazy_static = "1.4.0"
ndarray = { workspace = true }
ndarray-stats = { workspace = true }
numpy = "0.17.2"
serde = { workspace = true }
serde-pickle = { workspace = true }

[dependencies.pyo3]
version = "0.17.3"
features = ["auto-initialize"]
