[package]
name = "mfcc"
version = "0.2.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
aubio = { version = "0.2.1", features = ["pkg-config"] }
bytemuck = { workspace = true }
clap = { workspace = true }
futures = { version = "0.3.25", optional = true }
ndarray = { workspace = true, features = ["serde"] }
rayon = { version = "1.6.1" }
serde = { workspace = true }
serde-pickle = { workspace = true }
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread", "fs"], optional = true }

[dependencies.codec]
path = "../codec"

[features]
async = ["dep:futures", "dep:tokio"]
parallel = []
default = ["parallel"]
