[package]
name = "mfcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
aubio = "0.2.1"
bytemuck = "1.9.1"
bytes = "1.1.0"
colorgrad = "0.6.0"
itertools = "0.10.3"
ndarray = { version = "0.15.4", features = ["rayon"] }
ordered-float = "3.0.0"
plotters = "0.3.1"
rayon = "1.5.3"
