[package]
name = "restreamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
axum = { version = "0.6.1" }
codec.workspace = true
mfcc.workspace = true
serde.workspace = true
serde_with.workspace = true
tokio.workspace = true
tower = "0.4.13"
tower-http = { version = "0.3.5", features = ["full"] }
unstreamer = { version = "0.1.0", path = "../unstreamer" }
url = { workspace = true }
