[package]
name = "trainer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.10"
uuid = { version = "1.1.1", features = ["v4"] }
rmp = "0.8.11"
anyhow = { version = "1.0.57", features = ["backtrace"] }
rmp-serde = "1.1.0"
bytes = { version = "1.1.0", features = ["serde"] }
rayon = "1.5.3"
bytemuck = "1.9.1"
aubio = "0.2.1"
automl = { git = "https://github.com/cmccomb/rust-automl.git", features = [
  "nd",
] }
future-utils = "0.12.1"
futures = { version = "0.3.21", features = ["futures-executor"] }
ndarray = { version = "0.15.4", features = ["rayon"] }
tokio = { version = "1.19.2", features = ["full"] }

[dependencies.model]
version = "*"
path = "../model"

[dependencies.mfcc]
version = "*"
path = "../mfcc"
