[package]
name = "trainer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
rayon = "1.5.3"
ndarray = { version = "0.15.4", features = ["rayon", "serde"] }
bincode = "1.3.3"
tch = "0.8.0"
rand = "0.8.5"
clap = { version = "3.2.16", features = ["derive"] }
num_cpus = "1.13.1"
kdam = "0.2.2"
bytes = "1.2.0"

[dependencies.model]
version = "*"
path = "../model"

[dependencies.mfcc]
version = "*"
path = "../mfcc"
